# Week 11 - Earn-Back Points Assignment #1

These exercises are entirely optional, but they provide good practice. And you can use them to earn extra points toward your semester grade.  Each problem in this notebook can you earn you back up to 2 points.  There are key requirements, though. If your code does not following these rules, you will earn no points for your work.
* You MUST include docstrings that explain the purpose of your code.
* You MUST include at least 2 example tests in your docstrings for each function you write.
* You MUST run your docstrings within the notebook to show me your code and docstrings work correctly.
* You MUST submit your own individual work.  You may not collaborate with other students on these assignments.

There will be 4 assignments like this between now and the end of the semester, each with 4 problems, each worth 2 points, for a total of 32 points.

**If anything about the above rules is unclear, please message me on Canvas or via email**

---

## Earn-Back 1: Sunflower Health Plan Files

Sunflower Health Plan is one of Centene's state-specific health plans. If you aren't familiar with Centene, they are one of the largest healthcare maangement organizations the country and are headquartered here in St. Louis. Many of your colleagues from previous graduating classes now work at Centene. 

Sunflower Health Plan has posted links to two files on this page: https://www.sunflowerhealthplan.com/json.html

* https://www.sunflowerhealthplan.com/content/dam/centene/sunflower/json/KAPrintProviderDir_Prac.json
* https://www.sunflowerhealthplan.com/content/dam/centene/sunflower/json/KAPrintProviderDir_Prov.json

This entire problemset asks you to work with these files.

Your first step is to write a python function called **get_files(type)** where **type** is a string that contains one of two values: *practitioner* or *provider*.  Your function should download the correct file from the webpage above based on the string value passed to the function. The function should return the objects created by loading that JSON data.

**INPUT:** `'practitioneer'` or `'provider'`

**OUTPUT:** Python object based on the data from the appropriate file.


*Note that these files may take a minute for Python to download. They're big.*

In [1]:
from urllib.request import urlopen
import json
def get_files(type):
    """
    str>>str
    The function will pull a json file from the respective url provided being either 'Practitioner' or 'Provider'. 
    Below tests are wriiten to check if the function worked
    1. If the correct url is not inputted the function throws a message saying error receiving the data 
    and will not return the required json file. 
    2. The length of the provider file obtained is 23127. 

    >>> get_files('prov')
    Error receiving data, provide Practitioner or provider
    
    >>> len(get_files('provider'))
    23127
    
    """

    if type == 'provider':
        url_provider = ('https://www.sunflowerhealthplan.com/content/dam/centene/sunflower/json/KAPrintProviderDir_Prov.json')
        response = urlopen(url_provider)
        jsonData = json.loads(response.read())
        
    elif type == 'practitioner':
        url_practitioner = ('https://www.sunflowerhealthplan.com/content/dam/centene/sunflower/json/KAPrintProviderDir_Prac.json')
        response = urlopen(url_practitioner)       
        jsonData = json.loads(response.read())
                
    else:
        jsonData = None 
        print("Error receiving data, provide Practitioner or provider" )
        
    return jsonData

In [2]:
len(get_files('provider'))

23127

In [3]:
import doctest
doctest.run_docstring_examples(get_files, globals(), verbose=True)

Finding tests in NoName
Trying:
    get_files('prov')
Expecting:
    Error receiving data, provide Practitioner or provider
ok
Trying:
    len(get_files('provider'))
Expecting:
    23127
ok


## Earn-Back 2: What is this Data?

No coding for this part, so no docstrings or tests are required.

Explain to in 2-3 sentences, what do you see in these files? If you can't make sense of it from a healthcare business perspective, just tell me what you see in techincal terms.

Per the files provided, it projects information regarding the practitioners and/or the providers. The details for the provider includes the provider ID, location, Name,speciality, address, accreditation, pharmacy details. Whereas the practitioners data includes practitioner ID, provider ID, location, office hours. 
There could also be seen that some of the details are missing on both files (ex:- Board status, panel status,)

## Earn-Back 3: How many are closed on each Day of the Week

You'll see in the files a piece of information that tellsu us what the schedule is on every day of the week:

```json
'PROVIDER_ID': '387724',
 'LOCATION_ID': '626140',
 'NAME': 'Mercy Clinic Cardiology',
 'PROVIDER TYPE': 'GROUP PRACTICE',
 'NPI': '1215264817',
 'SPECIALTY': 'Multi-Specialty',
 'ADDRESS1': '3020 Saint Johns Boulevard',
 'ADDRESS2': 'Suite A1',
 'ADDRESS3': '',
 'CITY': 'Joplin',
 'STATE': 'MO',
 'ZIP': '64804',
 'COUNTY': 'Newton',
 'LATITUDE': '37.061',
 'LONGITUDE': '-94.536',
 'PHONE': '(417) 627-8566-(855) 420-7900',
 'AFTER HOUR PHONE': '',
 'FAX': '',
 'OFFICEHOURS_SU': 'Closed',
 'OFFICEHOURS_MO': '8:00 AM - 5:00 PM',
 'OFFICEHOURS_TU': '8:00 AM - 5:00 PM',
 'OFFICEHOURS_WE': '8:00 AM - 5:00 PM',
 'OFFICEHOURS_TH': '8:00 AM - 5:00 PM',
 'OFFICEHOURS_FR': '8:00 AM - 5:00 PM',
 'OFFICEHOURS_SA': 'Closed',
 'HANDICAP ACCESS': 'N',
 'WEBSITE': 'www.mercy.net',
 'PRODUCT 1': 'GP',

```

Write a function called **closed_by_day(data)** that takes one parameter (the data that came out of the Provider or Practitioner download) and outputs a dictionary of how many practitioneres / providers are closed on each day:
```json
{
    "Sunday": 1401,
    "Monday": 2,
    ...etc...
```

In [7]:
def closed_by_day(data):
    """(list) >> dict
    This function takes the json file from the previous function(get_files) as an input nd outputs a dictionary 
    of how many practitioneres / providers are closed on each day as an dictionary.
    
    >>> closed_by_day('provider')
    {'Sunday': 19380, 'Monday': 30, 'Tuesday': 2, 'Wednesday': 0, 'Thursday': 3, 'Friday': 4, 'Saturday': 156}
    
    >>> closed_by_day("provider")["Sunday"]
    19380
    
    """
    sunday = 0
    monday = 0
    tuesday = 0
    wednesday = 0
    thursday = 0
    friday = 0
    saturday = 0
    
    days = get_files(data)
    
    for week in days:
        if week["OFFICEHOURS_SU"]=="Closed":
            sunday += 1
        elif week["OFFICEHOURS_MO"]=="Closed":
            monday+= 1
        elif week["OFFICEHOURS_TU"]=="Closed":
            tuesday += 1         
        elif week["OFFICEHOURS_WE"]=="Closed":
            wednesday += 1   
        elif week["OFFICEHOURS_TH"]=="Closed":
            thursday+= 1 
        elif week["OFFICEHOURS_FR"]=="Closed":
            friday+= 1 
        elif week["OFFICEHOURS_SA"]=="Closed":
            saturday += 1            
        
    week_of_the_days = {'Sunday': sunday, 'Monday': monday, 'Tuesday': tuesday, 'Wednesday': wednesday, 'Thursday': thursday, 'Friday': friday, 'Saturday': saturday}
    
    return week_of_the_days
        
        
    

In [8]:
closed_by_day('provider')

{'Sunday': 19380,
 'Monday': 30,
 'Tuesday': 2,
 'Wednesday': 0,
 'Thursday': 3,
 'Friday': 4,
 'Saturday': 156}

In [9]:
import doctest
doctest.run_docstring_examples(closed_by_day, globals(), verbose=True)

Finding tests in NoName
Trying:
    closed_by_day('provider')
Expecting:
    {'Sunday': 19380, 'Monday': 30, 'Tuesday': 2, 'Wednesday': 0, 'Thursday': 3, 'Friday': 4, 'Saturday': 156}
ok
Trying:
    closed_by_day("provider")["Sunday"]
Expecting:
    19380
ok


## Earn-Back 4: Output to a file

Now, simply write a function named **to_csv(data, file)** that takes this summary view of information as a dictionary (the `data` parameter) and writes it out to a CSV file (the `file` parameter).

In [10]:
import pandas as pd

def to_csv(data,file):
    """(dictionary, str)
    
    The function provided here takes the summary view of information as a dictionary and writes it out to a CSV file (the file parameter). 
    
    >>> pd.read_csv("weekoffs_count.csv").values[0]
    array([19380,    30,     2,     0,     3,     4,   156])
    
    >>> pd.read_csv("weekoffs_count.csv").dtypes
    Sunday       int64
    Monday       int64
    Tuesday      int64
    Wednesday    int64
    Thursday     int64
    Friday       int64
    Saturday     int64
    dtype: object
    
    
    """
    
    import csv
    
    my_dict = {'Sunday': 19380,'Monday': 30,'Tuesday': 2,'Wednesday': 0,'Thursday': 3,'Friday': 4,'Saturday': 156}
    
    fields = ['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday']
    filename = "weekoffs_count.csv"
        
    with open(filename, 'w') as f:
        writer = csv.DictWriter(f, fieldnames = fields) 
        writer.writeheader()
        
        for key in data:
            writer.writerow(my_dict)
    
    return 
     

In [11]:
import pandas as pd
pd.read_csv("weekoffs_count.csv",skiprows = [1,2,3,4,5,6])

Sunday  Monday  Tuesday  Wednesday  Thursday  Friday  Saturday
0   19380      30        2          0         3       4       156

In [12]:
pd.read_csv("weekoffs_count.csv").values[0]

array([19380,    30,     2,     0,     3,     4,   156])

In [13]:
pd.read_csv("weekoffs_count.csv").dtypes

Sunday       int64
Monday       int64
Tuesday      int64
Wednesday    int64
Thursday     int64
Friday       int64
Saturday     int64
dtype: object

In [14]:
import doctest
doctest.run_docstring_examples(to_csv, globals(), verbose=True)

Finding tests in NoName
Trying:
    pd.read_csv("weekoffs_count.csv").values[0]
Expecting:
    array([19380,    30,     2,     0,     3,     4,   156])
ok
Trying:
    pd.read_csv("weekoffs_count.csv").dtypes
Expecting:
    Sunday       int64
    Monday       int64
    Tuesday      int64
    Wednesday    int64
    Thursday     int64
    Friday       int64
    Saturday     int64
    dtype: object
ok


## Submit your work to github in your week 11 folder by 11/18 11:59 PM